name: mobile
description: "LeetCode-like Quiz App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.4

  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  json_annotation: ^4.8.1

  # Authentication
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.32.0

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.5
  permission_handler: ^11.2.0
  device_info_plus: ^9.0.1

  # Charts & Analytics
  fl_chart: ^0.66.2

  # PDF & Export
  pdf: ^3.10.7
  path_provider: ^2.1.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/app.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
